sonar.projectKey=ohart-admin-nuxt
sonar.projectName=ohart-admin-nuxt

sonar.sources=app
sonar.tests=app,tests
sonar.test.inclusions=**/*.{test,spec}.{js,ts}
sonar.exclusions=**/*.d.ts,**/node_modules/**,**/.nuxt/**,**/.output/**,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
